### ISSUE TITLE
Melhoria1: Melhoria da tela de login

### ISSUE THREAD

**Issue by clara-ribeiro** [fga-eps-mds/2024.2-SENTINELA-DOC#100]
**Descrição**

Como usuário, eu gostaria de conseguir visualizar as vantagens na página inicial (login) e me interar dos benefícios de me filiar ao sindicato.

**Critérios de Aceitação**

- [x] Na página inicial (login) deve haver uma mensagem inicial, convidando o usuário a conhecer as vantagens de se filiar;
- [x] Na página inicial (login) deve haver um botão que leva o usuario até o conteúdo das vantagens/beneficios;
- [x] As vantagens devem ser exibidas na página inicial;
- [x] A página inicial deve ser responsiva e com boa usabilidade em mobile;

**Protótipo:**

Protótipo com modificações na interface:
- Página de Login com a chamada para a página de /vantagens: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5044-4559
- Mobile: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5044-4636

Protótipo sem modificações na interface:
- Login: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5278-5306&node-type=canvas&t=oM3Q7DfwoK8kirdg-0&scaling=min-zoom&content-scaling=fixed&page-id=5044%3A4371
- Mobile com card expandido: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5283-5678&node-type=canvas&t=oM3Q7DfwoK8kirdg-0&scaling=min-zoom&content-scaling=fixed&page-id=5044%3A4371

**Comment by clara-ribeiro** [comment]
Formulário de validação: https://forms.gle/ENyPWxjKutDhQQAv6

**Comment by JoaoPC10** [comment]
Eu contribui nesta Melhoria.
