### ISSUE TITLE
US17: Como administrador, gostaria de um relatório com base nesses arquivos retornos

### ISSUE THREAD

**Issue by clara-ribeiro** [fga-eps-mds/2024.2-SENTINELA-DOC#116]
Como Administrador, gostaria de poder visualizar o status de mensalidade dos contribuintes

- [ ] Exibir os contribuintes que tiveram atualização de status.
- [ ] Exibir o status anterior e o status atual
- [ ] Exibir os contribuintes pendentes primeiro 
- [ ] Ter a opção de mudar a situação da assinatura do contribuinte
- [ ] Poder visualizar mais detalhes do contribuinte (nome, cpf, matricula)
- [ ] Em caso de cancelar a filiação, ter como definir a data e motivo

Link do Protótipo: https://www.figma.com/design/fp984nJmbR3xHAqVM7ixsH/Protótipos-2024.2?node-id=6062-3183&t=JimMT39jp1eDTBgS-0

**Comment by Matheus-AM** [comment]
Critérios de aceitação aceitos. Protótipo previamente aceito, esperando que sejam feitas as mudanças já anotadas no protótipo: adicionar informações adicionais do sindicalizado selecionado (nome, cpf, matricula); poder definir a data e motivo de cancelamento.

**Comment by JoaoPC10** [comment]
Eu estou contribui nesta US.
