### ISSUE TITLE
US4: Exibir os benefícios de ser filiado em uma página pública

### ISSUE THREAD

**Issue by clara-ribeiro** [fga-eps-mds/2024.2-SENTINELA-DOC#82]
**Descrição**
Como um não filiado, quero visualizar os benefícios da filiação antes de me filiar na página inicial.

**Critérios de Aceitação**

- [x] O componente de vantagens deve puxar os benefícios ativos cadastrados no banco de dados.
- [x] O componente de vantagens deve ter um botão que envie para o formulário de filiação.
- [x] O componente de vantagens deve ser exibido na página inicial;
- [x] A UI deve seguir o padrão estabelecido, com cores, tipografia e botões coerentes com o restante do sistema.
- [x]  A página deve ser responsiva para dispositivos móveis.
- [x]  Cada benefício deve ser exibido de forma resumida (a principio com nome e um botão de saber mais, que irá abrir uma modal com a descrição do benefício).

**Protótipo:**

Protótipo com modificações na interface:
- Página /vantagens: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5064-265&node-type=canvas&t=99arc2CPDI3q1Wcb-0&scaling=min-zoom&content-scaling=fixed&page-id=5044%3A4371
- Mobile: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5128-5332&node-type=canvas&t=99arc2CPDI3q1Wcb-0&scaling=min-zoom&content-scaling=fixed&page-id=5044%3A4371

Protótipo sem modificações na interface:
- Vantagens: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5278-4614&node-type=canvas&t=oM3Q7DfwoK8kirdg-0&scaling=min-zoom&content-scaling=fixed&page-id=5044%3A4371
- Vantagens com card expandido: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5278-5423&node-type=canvas&t=oM3Q7DfwoK8kirdg-0&scaling=min-zoom&content-scaling=fixed&page-id=5044%3A4371
- Mobile: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5278-5208&node-type=canvas&t=oM3Q7DfwoK8kirdg-0&scaling=min-zoom&content-scaling=fixed&page-id=5044%3A4371
- Mobile com card expandido: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5283-5678&node-type=canvas&t=oM3Q7DfwoK8kirdg-0&scaling=min-zoom&content-scaling=fixed&page-id=5044%3A4371

**Comment by clara-ribeiro** [comment]
Formulário de aceitação: https://forms.gle/QMKb3EFaYL2jR8mt7
