### ISSUE TITLE
US3: Validar status do sindicalizado por QR Code

### ISSUE THREAD

**Issue by clara-ribeiro** [fga-eps-mds/2024.2-SENTINELA-DOC#83]
**Descrição:**
Como um gestor ou parceiro do sindicato, quero escanear o QR Code na carteirinha para validar se o afiliado está ativo, garantindo autenticidade.

**Critérios de Aceitação:**

- [ ]  O QR Code deve redirecionar para uma página que confirme o status ativo/inativo do afiliado.
- [ ]  A validação deve exibir Nome, CPF e Status caso o usuário seja ativo.
- [ ] A validação deve exibir Nome caso o usuário seja inativo.

**Protótipo**

**Comment by Matheus-AM** [comment]
Os critérios de aceitação fazem sentido. Mas não tem um protótipo. O que me faz entender que a validação descrita será so os dados. 
É isso mesmo? Não tem tela de validação? Vai ter um link nesse QRcode? Vai ter esses dados em texto? Se tem uma US para descrever melhor o QRcode é essa. Qual a solução para essa validação? 
Fluxos que eu penso: Ter um link no QRcode onde se coloca uma chave e aparece a validade do usuário. O que acham?

**Comment by daniso0412** [comment]
Para visualizar essa página, você deve:

Acessar a página inicial (http://191.252.203.28/)
Fazer o login (pode usar o seguinte acesso: email: [email](https://github.com/fga-eps-mds/2024.2-SENTINELA-DOC/issues/Sicrana@testesindpol.com) e senha: 123456)
Em seguida, após acessar a rota da carteirinha e encontrar as informações dela, você encontrar um qr-code que poderar direcionar sua camera de celular que redirecionará para uma pagina para validar o status do sindicalizado

Formulário de validação: https://forms.gle/UXijY5SP9uoxnxAF7
