### ISSUE TITLE
US2: Disponibilizar o download da carteirinha do sindicalizado

### ISSUE THREAD

**Issue by clara-ribeiro** [fga-eps-mds/2024.2-SENTINELA-DOC#84]
**Descrição:**
Como um afiliado, quero baixar minha carteira digital em PDF para salvá-la ou imprimi-la quando necessário.

**Critérios de Aceitação:**

- [ ]  O afiliado deve conseguir baixar a carteirinha em um formato PDF.
- [ ]  O layout do PDF deve conter todas as informações presentes na carteirinha digital.
- [ ]  A funcionalidade de download deve estar disponível apenas para sindicalizados ativos.

**Protótipo:**
Botão de download: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5031-4345&node-type=canvas&t=6YFYjDodM8qiLViS-0&scaling=min-zoom&content-scaling=fixed&page-id=914%3A2508

PDF: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5102-471&node-type=canvas&t=6YFYjDodM8qiLViS-0&scaling=min-zoom&content-scaling=fixed&page-id=914%3A2508

**Comment by daniso0412** [comment]
**Prototipo da Carteirinha Digital em PDF**
https://www.figma.com/design/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=914-2508&node-type=canvas&t=ku2Dg4pBIiLjdEU1-0

<img width="307" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTd5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--897dc8044595d2c4bb46ed6efce6169f3f9d905d/Captura%20de%20tela%202024-11-28%20140120.png" alt="Captura de tela 2024-11-28 140120.png" />

**Comment by Matheus-AM** [comment]
Critérios de aceitação estão certos.
Mesmas observações que faço da US01. Essa preview até pode ser útil, mas o importante é ele ter acesso ao pdf da carteirinha. O protótipo está legal, mas poderia trocar o numero por "QRcode de validação".

**Comment by clara-ribeiro** [comment]
Formulário de validação: https://forms.gle/u8SfY1KwqbAW9XTQ8
