### ISSUE TITLE
US1 - Gerar carteirinha do sindicalizado

### ISSUE THREAD

**Issue by clara-ribeiro** [fga-eps-mds/2024.2-SENTINELA-DOC#85]
**Descrição**

Como um afiliado eu quero gerar minha carteira digital com informações pessoais para usá-la como prova de participação.

**Critérios de aceitação**

- [ ] A carteirinha deve conter NOME DO TITULAR, DATA NASCIMENTO, DATA DE EXPEDIÇÃO,  CPF, VALIDADE e Logo.
- [ ] Contato do sindpol
- [ ] O sindicalizado deve estar ativo para conseguir acessar a carteirinha em seu perfil
- [ ] Ao ser desfiliado a carteirinha deve ser revogada
- [ ] Quem não for sindicalizado não deve ter acesso a área da carteirinha

**Protótipo**
[https://www.figma.com/design/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=914-2508&node-type=canvas&t=ku2Dg4pBIiLjdEU1-0](https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5031-4345&node-type=canvas&t=6YFYjDodM8qiLViS-0&scaling=min-zoom&content-scaling=fixed&page-id=914%3A2508)

**Comment by clara-ribeiro** [comment]
- Nome;
- Matrícula;
- Data de filiação;

**Comment by daniso0412** [comment]
**Prototipo da Carteirinha Digital**
https://www.figma.com/design/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=914-2508&node-type=canvas&t=ku2Dg4pBIiLjdEU1-0

**Comment by clara-ribeiro** [comment]
Formulário de validação: https://forms.gle/zhDHZ4PLnPt8opy68
