### ISSUE TITLE
US6: Informação de contato

### ISSUE THREAD

**Issue by clara-ribeiro** [fga-eps-mds/2024.2-SENTINELA-DOC#87]
**Descrição**

Como usuário, quero encontrar informações de contato do sindicato no rodapé, para esclarecer dúvidas ou obter mais informações.

**Critérios de aceitação**

- [x] Todas as páginas do sistema devem exibir um rodapé com informações de contato do sindicato.
- [x] O rodapé deve conter: Telefone, E-mail, Endereço, links para redes sociais e para o site (sindpol.org,br).
- [x] O design do rodapé deve ser discreto, mas legível, e consistente entre as páginas.
- [x]  O rodapé deve ser responsivo para dispositivos móveis.

**Protótipo**
Rodapé ao final da página: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5044-4559
Mobile: https://www.figma.com/proto/fp984nJmbR3xHAqVM7ixsH/Prot%C3%B3tipos-2024.2?node-id=5044-4636&node-type=canvas&t=99arc2CPDI3q1Wcb-0&scaling=min-zoom&content-scaling=fixed&page-id=5044%3A4371

**Comment by clara-ribeiro** [comment]
Formulário de validação: https://forms.gle/yCoharNE7n78XxUR6
